var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                               o          o      xx!xx          ",
   "                                    o o        o          o      x!!!x          ",
   "                               o           x   o x   xx          xx!xx          ",
   "                               o    xx!!xx                         xvx          ",
   "                        o      o          o                                 xx  ",
   "  xx     y   y       !  x            y  !  x  o o          y       y         x  ",
   "  x                     o      !            o             o                  x  ",
   "  x           o    x    x   x     x      xxxxx      x                      o x  ",
   "  x          xxx        o                                                  o x  ",
   "  x  @        o             !   o          o            o        xx!xx     o x  ",
   "  xxxxxx!!xxxx!!xx!!xxxx!!xxxx!  x!xxx!!xx!!xxxx!!xxx!  o  !xxxxxx   xxxxxxxxx  ",
   "                              x   x                  x  x  x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x             y         o                                           x!x  ",
   "                                      x!!x                     x!!x                                          x!x  ",
   "                                      x!!xxxxxxxxxx           xx                                             x!x  ",
   "                                      xx!!!!!!!!!!xx         xx                                              x!x  ",
   "                                       xxxxxxxxxx!!x      x vx                                    o   o   o  x!x  ",
   "                                                xx!x   o     x     o   o                              w     xx!x  ",
   "                                                 x!x   x     x                   xxxxx        xxxxxxxxxxxxxxx!!x  ",
   "                                                xvx      xx  x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                        xx    xx!!!!!!!!!!!xx            v                        ",
   "                                                      xx       xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                  y              !!!           x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                 !!!           x     x                             xx        x                    ",
   "                !o!o!                          xx    x       w                     x         x                    ",
   "                                               x     x      o!!o     x   x                   x                    ",
   "               xxxxxxx    y   xxx   xxx              x                             !     v   x                    ",
   "              xx     xx         x   x                x     xxxxxx    xx   x   xxxxxxxxx       x                   ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @    x           x      x  x   x          x     x    x   v       x   x   x               x                   ",
   "    xxx      xx         x           x                x      x          x   xxxxx   xxxxxx      x                  ",
   " xx x x      x  x         xx   xx o xx         x         x x          x     o     x x         x                   ",
   " !! x x!!!!!!x    x     x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                   ",
   " !! x x!!!!!!x     x o xx!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x       x x!!!!!x    o    !w      !    xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x             !      xx!!!!!!xx  !                     xxxxxxx                       ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!x!!xxx!!x!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        v                                                                    ",
   "                                        v                                                                     ",
   "                                        v                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                           !!!        !!!  xxx                                ",
   "                                                           !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   o!!o   x       xxx                            ",
   "                                      x   x                 x                 x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xvx                               ",
   "                                     xx   xx          x             o                                         ",
   "                                      x   x= = = =    x            xxx       y                                ",
   "                                 x    x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xvx       xxx          y                   ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x  x                                      x!!!x                xxx  ",
   "  x x                         x    x!x      o  x                           w         xxx                 x x  ",
   "  x                           x    xvx     xxxxxx    y      y    y       xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |!!!!|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               o!!!o       x    xxx    x         o                              xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  !! !!                    xxx        x  ",
   "  x      @                    x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
